CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE "VideoStatus" AS ENUM (
  'UPLOADING',
  'UPLOADED',
  'TRANSCODING',
  'PREVIEW_READY',
  'TRANSCODE_FAILED',
  'APPROVAL_REQUESTED',
  'APPROVED',
  'REJECTED',
  'PUBLISHING',
  'PUBLISHED',
  'PUBLISH_FAILED'
);

CREATE TYPE "UserRole" AS ENUM (
  'CREATOR',
  'EDITOR',
  'ADMIN'
);

CREATE TYPE "PublishStatus" AS ENUM (
  'PENDING',
  'RUNNING',
  'COMPLETED',
  'FAILED'
);

CREATE TYPE "YouTubePrivacy" AS ENUM (
  'PRIVATE',
  'UNLISTED',
  'PUBLIC'
);
